In [3]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import numpy as np

In [4]:
num_in = 34
num_out = 4

csv_file = "dataset.csv"
save_name = "first_weight.h5"

In [5]:
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(30, input_dim=num_in, activation='relu'))
    model.add(Dense(20, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(num_out, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model


In [ ]:
# # define baseline model
# def baseline_model():
#     # create model
#     model = Sequential()
#     model.add(Dense(20, input_dim=15, activation='relu'))
#     model.add(Dense(10, input_dim=20, activation='relu'))
#     model.add(Dense(num_colors, activation='softmax'))
#     # Compile model
#     model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#     return model


In [6]:
# load dataset
dataframe = pandas.read_csv(csv_file, header=None).sort_values(num_in)
dataset = dataframe.values

X = dataset[:,0:num_in]
Y = dataset[:,num_in]

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)



In [7]:
dataframe[num_in].unique()

array([0, 1, 2, 3])

In [8]:
X

array([[0.078 , 0.095 , 0.0897, ..., 0.7865, 0.1091, 0.8117],
       [0.1112, 0.0986, 0.1255, ..., 0.8138, 0.0495, 0.8056],
       [0.1119, 0.099 , 0.1263, ..., 0.8159, 0.0497, 0.8079],
       ...,
       [0.0705, 0.2408, 0.0792, ..., 0.8941, 0.0791, 0.8765],
       [0.0706, 0.247 , 0.079 , ..., 0.8931, 0.0803, 0.8799],
       [0.0719, 0.2493, 0.0811, ..., 0.8851, 0.0755, 0.875 ]])

In [9]:
Y

array([0., 0., 0., ..., 3., 3., 3.])

In [10]:
dataframe.head

<bound method NDFrame.head of           0       1       2       3       4       5       6       7      8   \
0     0.0780  0.0950  0.0897  0.0759  0.0677  0.0774  0.1103  0.0934  0.057   
427   0.1112  0.0986  0.1255  0.0812  0.1036  0.0791  0.1526  0.0997 -1.000   
428   0.1119  0.0990  0.1263  0.0818  0.1044  0.0795  0.1534  0.1010 -1.000   
429   0.1129  0.0980  0.1275  0.0812  0.1054  0.0783  0.1544  0.1011 -1.000   
430   0.1124  0.0990  0.1270  0.0821  0.1050  0.0791  0.1545  0.1018 -1.000   
...      ...     ...     ...     ...     ...     ...     ...     ...    ...   
2209  0.0712  0.2429  0.0797  0.2286  0.0651  0.2312  0.1034  0.2389 -1.000   
2210  0.0707  0.2432  0.0792  0.2288  0.0646  0.2316  0.1033  0.2392 -1.000   
2211  0.0705  0.2408  0.0792  0.2266  0.0641  0.2296  0.1028  0.2382 -1.000   
2204  0.0706  0.2470  0.0790  0.2320  0.0643  0.2355  0.1033  0.2415 -1.000   
2617  0.0719  0.2493  0.0811  0.2345  0.0649  0.2372  0.1037  0.2458 -1.000   

          9   ...    

In [11]:
np.max(encoded_Y)

3

In [13]:
dummy_y

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [12]:
m = baseline_model()
m.fit(X, dummy_y, epochs = 300, batch_size = 50, verbose = 0)


2023-06-10 18:15:58.131479: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-06-10 18:15:58.146827: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [13]:
scores = m.evaluate(X, dummy_y, verbose=0)
print("%s: %.2f%%" % (m.metrics_names[1], scores[1]*100))

accuracy: 100.00%


In [14]:
predictions = m.predict(X)
np.argmax(predictions, axis=1)

82/82 [==============================] - 0s 345us/step


array([0, 0, 0, ..., 3, 3, 3])

In [15]:
a = [[0.3728, 0.2994, 0.4249, 0.2303, 0.3271, 0.2439, 0.5126, 0.2638, 0.28, 0.2872, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]]

p = m.predict(a)
print(p)
np.argmax(p, axis=1)

1/1 [==============================] - 0s 18ms/step
[[1.2380297e-02 1.2704403e-20 9.8761976e-01 5.6451491e-18]]


array([2])

In [16]:
m.save(save_name)

In [ ]:
from keras import models

In [ ]:
reconstructed_model = models.load_model(save_name)


In [ ]:
a = [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
for i in range(10):p = reconstructed_model.predict(a)
print(p)
np.argmax(p, axis=1)

NameError: ignored

In [ ]:
!zip -r /content/wtf_shape_det.zip /content/wtf_shape_det

  adding: content/wtf_shape_det/ (stored 0%)
  adding: content/wtf_shape_det/saved_model.pb (deflated 88%)
  adding: content/wtf_shape_det/fingerprint.pb (stored 0%)
  adding: content/wtf_shape_det/variables/ (stored 0%)
  adding: content/wtf_shape_det/variables/variables.data-00000-of-00001 (deflated 15%)
  adding: content/wtf_shape_det/variables/variables.index (deflated 61%)
  adding: content/wtf_shape_det/keras_metadata.pb (deflated 88%)
  adding: content/wtf_shape_det/assets/ (stored 0%)
